[package]
name = "gpfreqs"
version = "0.0.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = "0.38.2"
clap = "3.0.0-beta.4"
