[package]
name = "gpfreqs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = { version = "1.0.21", features = ["zlib-ng-compat"], default-features = false }
clap = "3.0.0-beta.4"
